name: Run GRChombo Tests (Clang)

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      CHOMBO_HOME: ${{ github.workspace }}/Chombo/lib
      OMP_NUM_THREADS: 1
      OMPI_CXX: clang++

    steps:
    - name: Checkout Chombo
      uses: actions/checkout@v3
      with:
        repository: GRChombo/Chombo
        path: Chombo

    - name: Checkout GRChombo
      uses: actions/checkout@v3
      with:
        path: GRChombo

    - name: Install Chombo dependencies
      run: |
        # First update package repository mirrors
        sudo gem install apt-spy2
        sudo apt-spy2 check
        sudo apt-spy2 fix --commit
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install csh libhdf5-dev libhdf5-openmpi-dev openmpi-bin libblas-dev liblapack-dev libgetopt-complete-perl

    - name: Build Chombo
      run: |
        cp $GITHUB_WORKSPACE/GRChombo/InstallNotes/MakeDefsLocalExamples/ubuntu-clang.Make.defs.local $CHOMBO_HOME/mk/Make.defs.local
        make -j 4 AMRTimeDependent AMRTools BaseTools BoxTools
      working-directory: ${{ env.CHOMBO_HOME }}

    - name: Build GRChombo Tests
      run: make test -j 4
      working-directory: ${{ github.workspace }}/GRChombo

    - name: Run GRChombo Tests
      run: make run -j 2
      working-directory: ${{ github.workspace }}/GRChombo
